### ISSUE TITLE
thread error

### ISSUE THREAD

**Issue by luomo1301532** [ra1nty/DXcam#22]
In the game, resolution switching often leads to thread interruption. Should timeout support customization

Exception in thread DXCamera:
Traceback (most recent call last):
  File "D:\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "F:\IdeaProjects\yolov5\venv\lib\site-packages\dxcam\dxcam.py", line 208, in __capture
    self.stop()
  File "F:\IdeaProjects\yolov5\venv\lib\site-packages\dxcam\dxcam.py", line 142, in stop
    self.__thread.join(timeout=10)
  File "D:\Python\Python37\lib\threading.py", line 1041, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

**Comment by luomo1301532** [comment]
Traceback (most recent call last):
  File "F:\IdeaProjects\yolov5\venv\lib\site-packages\dxcam\dxcam.py", line 179, in __capture
    self.__frame_buffer[self.__head] = frame
ValueError: could not broadcast input array from shape (300,300,4) into shape (900,1600,4)

**Comment by luomo1301532** [comment]
This should be a bug. It is necessary to change the screen resolution

**Comment by ra1nty** [comment]
closing as latest release address the issue
