### ISSUE TITLE
Installation from pipy is failing.

### ISSUE THREAD

**Issue by Pondiniii** [ra1nty/DXcam#4]
Hi,
I tried to install DXcam using command provided in the description: ```
pip install -i https://test.pypi.org/simple/ dxcam ```but it throws this error:
```
PS C:\Users\Administrator\PycharmProjects\dxcam> pip install -i https://test.pypi.org/simple/ dxcam
>>
Looking in indexes: https://test.pypi.org/simple/, https://pypi.ngc.nvidia.com
Collecting dxcam
  Downloading https://test-files.pythonhosted.org/packages/9e/d6/c47112d04c49175beb00bf54e4db71fe41d4f1533b0e202bdd8534ad5320/dxcam-0.0.3-py3-none-any.whl (9.5 kB)
Collecting numpy
  Downloading https://test-files.pythonhosted.org/packages/d5/80/b947c574d9732e39db59203f9aa35cb4d9a5dd8a0ea2328acb89cf10d6e3/numpy-1.9.3.zip (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 16.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting dxcam
  Downloading https://test-files.pythonhosted.org/packages/a2/0a/5a1130ee405a08b4cb28f80393ce9dc4d85e6db7475e80b8f8663efd7154/dxcam-0.0.2-py3-none-any.whl (9.3 kB)
ERROR: Cannot install dxcam==0.0.2 and dxcam==0.0.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    dxcam 0.0.3 depends on comtypes
    dxcam 0.0.2 depends on comtypes

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

To fix it, I tried to install dependencies manually first using this command:
```pip install opencv-python numpy comtypes```
it returned:
```Successfully installed comtypes-1.1.11 numpy-1.21.6 opencv-python-4.5.5.64```

Then I typed:
```pip install -i https://test.pypi.org/simple/ dxcam==0.0.3```

```
PS C:\Users\Administrator\PycharmProjects\dxcam> pip install -i https://test.pypi.org/simple/ dxcam==0.0.3
Looking in indexes: https://test.pypi.org/simple/, https://pypi.ngc.nvidia.com
Collecting dxcam==0.0.3
  Downloading https://test-files.pythonhosted.org/packages/9e/d6/c47112d04c49175beb00bf54e4db71fe41d4f1533b0e202bdd8534ad5320/dxcam-0.0.3-py3-none-any.whl (9.5 kB)
Requirement already satisfied: comtypes in c:\users\administrator\pycharmprojects\dxcam\venv\lib\site-packages (from dxcam==0.0.3) (1.1.11)
Requirement already satisfied: opencv-python in c:\users\administrator\pycharmprojects\dxcam\venv\lib\site-packages (from dxcam==0.0.3) (4.5.5.64)
Requirement already satisfied: numpy in c:\users\administrator\pycharmprojects\dxcam\venv\lib\site-packages (from dxcam==0.0.3) (1.21.6)
Installing collected packages: dxcam
Successfully installed dxcam-0.0.3

```

Output of following command says it installed successfully, but when I try to run the following code:
```python
import dxcam
camera = dxcam.create()
camera.grab()
```
I get this:

```
C:\Users\Administrator\PycharmProjects\dxcam\venv\Scripts\python.exe C:/Users/Administrator/PycharmProjects/dxcam/test.py
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/dxcam/test.py", line 1, in <module>
    import dxcam
  File "C:\Users\Administrator\PycharmProjects\dxcam\venv\lib\site-packages\dxcam\__init__.py", line 2, in <module>
    from dxcam.dxcam import DXCamera, Output, Device
  File "C:\Users\Administrator\PycharmProjects\dxcam\venv\lib\site-packages\dxcam\dxcam.py", line 7, in <module>
    from dxcam.core import Device, Output, StageSurface, Duplicator
ModuleNotFoundError: No module named 'dxcam.core'
```

I Tried to git-clone folder (dxcam) into venv/lib/dxcam/ but it didn't help. Now I get:

```
C:\Users\Administrator\PycharmProjects\dxcam\venv\Scripts\python.exe C:/Users/Administrator/PycharmProjects/dxcam/test.py
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/dxcam/test.py", line 1, in <module>
    import dxcam
  File "C:\Users\Administrator\PycharmProjects\dxcam\venv\lib\site-packages\dxcam\__init__.py", line 2, in <module>
    from dxcam.dxcam import DXCamera, Output, Device
  File "C:\Users\Administrator\PycharmProjects\dxcam\venv\lib\site-packages\dxcam\dxcam\__init__.py", line 2, in <module>
    from dxcam.dxcam import DXCamera, Output, Device
ImportError: cannot import name 'DXCamera' from 'dxcam.dxcam' (C:\Users\Administrator\PycharmProjects\dxcam\venv\lib\site-packages\dxcam\dxcam\__init__.py)

Process finished with exit code 1
```
Btw. I tried it on Arch Linux (py3.9) and Windows 10 (using py3.7 and 3.9).

**Comment by Pondiniii** [comment]
Workaround:
`git clone https://github.com/ra1nty/DXcam`
`cd DXcam`
`pip install opencv-python numpy comtypes`
`cp /benchmarks/dxcam_max_fps.py dxcam_max_fps.py`
`python dxmax_max_fps.py`

**Comment by ra1nty** [comment]
Hi Pondiniii,

Thanks for trying out my library. Apologize -- I made a stupid mistake when creating setup.cfg.
Please try installation again from test pypi:
```
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple dxcam
```
The issue should be fixed now.

Thanks.
