### ISSUE TITLE
AttributeError: 'DXCamera' object has no attribute 'is_capturing' 

### ISSUE THREAD

**Issue by lon91ong** [ra1nty/DXcam#55]
Like #49 , but my OS is windows7 and python version is 3.8.16
Traceback info:
```
Exception ignored in: <function DXCamera.__del__ at 0x00000000121BDDC0>
Traceback (most recent call last):
  File "E:\Python\DXcam\dxcam\dxcam.py", line 243, in __del__
    self.release()
  File "E:\Python\DXcam\dxcam\dxcam.py", line 238, in release
    self.stop()
  File "E:\Python\DXcam\dxcam\dxcam.py", line 138, in stop
    if self.is_capturing:
AttributeError: 'DXCamera' object has no attribute 'is_capturing'
```

I have download the new version source code from github and install with `pip install --editable .` , no help with the problem

**Comment by Jonathan0328** [comment]
I have 2 graphic cards in my computer. I have the same issue with you too.
Here is how I solved this problem 
![image](https://user-images.githubusercontent.com/87103479/222929145-5bea5869-9d06-4986-ab17-ce4c533ee62d.png)
![image](https://user-images.githubusercontent.com/87103479/222929152-78db9f38-a3fc-428f-9272-35afc9cea9a2.png)
I changed my graphic preference  from  Nvidia Geforce RTX 3060 to AMD Radeon(TM) Graphics.
Then the problem solved.
Hope it was helpful to you. Wish you have  a nice day~

P.S.  Graphics settings -> find python.exe  -> Graphic preference  -> Power saving

**Comment by alpgithubx** [comment]
doesn't work? can someone help

**Comment by eusolobehe1898** [comment]
I have the same problem only on windows 7, any solution?

**Comment by niloriver** [comment]
Same issue here. Using Windows 11. 

2 graphic cards. Intel Graphics and NVIDIA 2060.

**Comment by Alexandros444** [comment]
Hello, I have the Same Problem, on Windows 10.
Using Python 3.10 from the Microsoft Store.

On my other System, Win10 Python 3.11 downloaded on the Python Website, everything is working fine.
